# run: conda env create --file environment.yml
name: jira-metrics2
channels: !!python/tuple
- defaults
dependencies:
- pip
- matplotlib <3.0
- numpy
- pandas==0.20.3
- python==3.6.8
- scipy
- seaborn
- statsmodels
- xlsxwriter
- pip:
  - dateparser==0.6.0
  - jira==1.0.7
  - jira_metrics_extract
  - html2text
